version: "3.8"

services:
  document-server:
    build:
      context: .
      dockerfile: apps/document-server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes: []

