packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  vite: npm:rolldown-vite@latest
  vitest: ^3.2.4
  tsdown: 0.11.13
  tsx: ^4.20.3
  typescript: ^5.8.3
  husky: ^9.1.7
  '@vitest/ui': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@types/node': ^22.16.0
  '@vitejs/plugin-react-swc': ^3.10.2
  vite-tsconfig-paths: ^5.1.4
  '@changesets/cli': ^2.29.5
  vite-bundle-analyzer: ^0.20.2
  vite-plugin-inspect: ^11.3.0
  next: ^15.3.5
  tailwindcss: ^4.1.11
  '@tanstack/react-query': ^5.81.5
  zod: ^3.25.73

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
