packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  vite: ^6.3.5
  vitest: '^3.1.3'
  tsdown: "^0.11"
  tsx: ^4.19.4
  typescript: ^5.8.3
  'husky': '^9.1.7'
  '@vitest/ui': '^3.1.3'
  '@vitest/coverage-v8': '^3.1.3'
  '@types/node': ^22.15.14
  '@vitejs/plugin-react-swc': ^3.9.0
  'vite-tsconfig-paths': ^5.1.4
  '@changesets/cli': ^2.29.3
  'vite-bundle-analyzer': ^0.20.1
  'vite-plugin-inspect': ^11.0.1
  next: ^15.3.1
  tailwindcss: ^4
  '@tanstack/react-query': ^5.59.15
  zod: ^3.25.67

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19
    '@types/react-dom': ^19
