export const AuthError = [
  // NOTE: AUTH_ERROR
  'USERNAME_TOO_LONG',
  'USERNAME_TOO_SHORT',
  'USERNAME_INVALID',

  // NOTE: PASSWORD_ERROR
  'PASSWORD_TOO_LONG',
  'PASSWORD_TOO_SHORT',
  'PASSWORD_INVALID',

  // NOTE: EMAIL_ERROR
  'EMAIL_INVALID',

  // NOTE: NAME_ERROR
  'NAME_INVALID',

  // NOTE: AUTH_ERROR
  'INVALID_CREDENTIALS',
  'UNAUTHORIZED',
] as const
