export const ZodError = [
  // Zod
  'ZOD_EXPECTED_JSON',
  'ZOD_EXPECTED_STRING',
  'ZOD_EXPECTED_NUMBER',
  'ZOD_EXPECTED_BOOLEAN',
  'ZOD_EXPECTED_ARRAY',
  'ZOD_TOO_LONG',
  'ZOD_TOO_SHORT',
  'ZOD_INVALID',
  'ZOD_FAILED_TO_PARSE',
] as const
