version: '3.8'
name: gentleduck-colab

services:
  # --- NestJS App ---
  app:
    container_name: document-server-dev
    build:
      context: ..
      dockerfile: apps/document-server/Dockerfile
    env_file:
      - ../apps/document-server/.env.dev
    ports:
      - '3000:3000'
    volumes:
      - ..:/app:cached
      - /app/node_modules
    command: pnpm --filter=document-server run start:dev
    networks:
      - nest-net
      - elk
    depends_on:
      - mongo
      - redis
      - elasticsearch
      - logstash

  # --- MongoDB ---
  mongo:
    container_name: mongo-dev
    image: mongo:7.0
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
      MONGO_INITDB_DATABASE: nestdb
    volumes:
      - mongo-dev-data:/data/db
    networks:
      - nest-net

  # --- Redis ---
  redis:
    container_name: redis-dev
    image: redis:7
    restart: always
    ports:
      - '6380:6379'
    networks:
      - nest-net

  # --- Kibana ---
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic2
      - ELASTICSEARCH_PASSWORD=securepassword
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2ZXI6dklybXktYl9UdmV1eDg4QW9hSUowZw
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # --- Elasticsearch ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=false
      - ELASTIC_PASSWORD=securepassword
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  # --- Logstash ---
  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
  mongo-dev-data:

networks:
  nest-net:
    driver: bridge
  elk:
    driver: bridge

