version: '3.8'

services:
  app:
    container_name: document-server-prod
    build:
      context: ../.. # monorepo root
      dockerfile: apps/document-server/Dockerfile # production Dockerfile
    env_file:
      - .env.prod
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    restart: always
    networks:
      - nest-net

  mongo:
    container_name: mongo-prod
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-prod-data:/data/db
    networks:
      - nest-net

volumes:
  mongo-prod-data:

networks:
  nest-net:
    driver: bridge

