version: '3.8'

services:
  app:
    container_name: document-server-dev
    build:
      context: ../..
      dockerfile: apps/document-server/Dockerfile.dev # development Dockerfile
    env_file:
      - .env.dev
    ports:
      - '3000:3000'
    volumes:
      - ../..:/app # mount whole monorepo for live updates
      - /app/node_modules # avoid overwriting node_modules
    command: pnpm --filter document-server dev
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - redis
    networks:
      - nest-net

  mongo:
    container_name: mongo-dev
    image: mongo:7.0
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-dev-data:/data/db
    networks:
      - nest-net
  redis:
    container_name: redis-dev
    image: redis:7
    restart: always
    ports:
      - '6380:6379'
    networks:
      - nest-net
    tty: true
    stdin_open: true

volumes:
  mongo-dev-data:

networks:
  nest-net:
    driver: bridge

